config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#new_guest"
  end

  root to: "public/homes#top"
  get "about"=> "public/homes#about"
  get "admin"=> "admin/homes#top"
  patch "members/withdraw"=> "public/members#withdraw"
  get "search" => "public/searches#search"

  #【会員側】Deviseを使った新規登録画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "members" => "public/members#dummy"

  #【会員側】テーマ投稿画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "/jobs/:job_id/themes" => "public/themes#dummy"

  #【管理者側】ジャンル名編集画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "/admin/genres/:id" => "admin/genres#dummy"

  namespace :admin do
    resources :members, only: %i(update edit show index) do
      member do
        get :member_jobs
        get :member_themes
      end
    end
    resources :genres, only: %i(index edit create update)
    resources :jobs, only: %i(index show edit update)
    resources :themes, only: %i(index)
    resources :jobs do
      resources :themes, only: %i(edit update) do
        get :theme_in_job, on: :collection
      end
    end
    resources :reports, only: %i(index show edit update)
  end

  #【管理者側】テーマ編集画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "admin/jobs/:job_id/themes/:id" => "admin/themes#dummy"

  scope module: :public do
    resources :members, only: %i(update edit show) do
      get :confirm, on: :collection
      member do
        get :member_jobs
        get :member_themes
        get :member_favorites
        get :member_comment_replies
      end
    end
    resources :jobs, only: %i(new create index show) do
      resources :themes, only: %i(new create show) do
        resources :comments, only: %i(create destroy) do
          resource :favorites, only: %i(create destroy)
          resources :reports, only: %i(new create)
          resources :replies, only: %i(index new create destroy)
        end
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  GUEST_EMAIL = "guest@example.com"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :jobs, dependent: :destroy
  has_many :themes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :replies, dependent: :destroy

  validates :last_name, presence: true, length: { maximum: 10 }
  validates :first_name, presence: true, length: { maximum: 10 }
  validates :nickname, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true
  validates :belong, presence: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/No_image.png")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end

    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  #退会済みのユーザーが同じアカウントでログイン出来ないようにするための制約
  #退会していなければtrueを返す
  def active_for_authentication?
    super && (!is_deleted?)
  end

  def self.guest
    find_or_create_by!(email: GUEST_EMAIL) do |member|
      #SecureRandom:ランダムパスワードにすることで変更されることを防ぐ。
      #.urlsafe_base64:ランダムで URL-safe な base64 文字列を生成して返す。
      member.password = SecureRandom.urlsafe_base64
      member.last_name = "ゲスト"
      member.first_name = "ゲスト"
      member.nickname = "ゲスト"
      member.belong = "転職を検討中"
    end
  end

  def guest?
    email == GUEST_EMAIL
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::AdminController

  def index
    @members = Member.page(params[:page]).per(5)
  end

  def show
    @member = Member.find(params[:id])
  end


  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
      if @member.update(update_admin_params)
        redirect_to admin_member_path(@member), notice: "更新を完了しました!"
      else
        flash[:notice] = "更新が正常に行われませんでした。内容をご確認ください。"
        render :edit
      end
  end

  def member_jobs
    @member = Member.find(params[:id])
    @jobs = @member.jobs.order("created_at DESC").page(params[:page]).per(10)
  end

  def member_themes
    @member = Member.find(params[:id])
    @themes = @member.themes.order("created_at DESC").page(params[:page]).per(10)
  end

  private
    def update_admin_params
      params.require(:member).permit(:last_name, :first_name, :nickname, :email, :introduction, :belong, :is_deleted, :profile_image)
    end

end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
  include HasIsPublished
  include HasIsChecked
  include HasContact

  def deleted_message(instance)
    if instance.is_deleted?
      tag.div "退会", class: "text-danger font-weight-bold"
    else
      tag.div "有効", class: "text-success font-weight-bold"
    end
  end
end

app/views/admin/members/edit.html.erb
<div class="container p-4">
    <div class="row justify-content-center py-4">
      <h3>会員情報編集</h3>
    </div>

    <div class="row justify-content-center p-4">
      <div class="w-75">

        <%= form_with model: @member, url: admin_member_path(@member.id), local:true do |f| %>

          <div class="form-group">
            <div class="row">
              <div class="col-md-4 text-left text-md-center">
                <%= f.label :profile_image, "プロフィール画像" %>
              </div>
              <div class="col-md-8">
                <%= f.file_field :profile_image, accept: "image/*" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-md-4 text-left text-md-center">
                <%= f.label :name, "名前（姓/名）" %>
              </div>
              <div class="col-md-8">
                <div class="row">
                  <div class="col-md-6">
                    <%= f.text_field :last_name, placeholder: "姓", class: "form-control" %>
                  </div>
                  <div class="col-md-6">
                    <%= f.text_field :first_name, placeholder: "名", class: "form-control" %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-md-4 text-left text-md-center">
                <%= f.label :email, "メールアドレス" %>
              </div>
              <div class="col-md-8">
                <%= f.email_field :email, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-md-4 text-left text-md-center">
                <%= f.label :nickname, "ニックネーム" %>
              </div>
              <div class="col-md-8">
                <%= f.text_field :nickname, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-md-4 text-left text-md-center">
                <%= f.label :introduction, "自己紹介文" %>
              </div>
              <div class="col-md-8">
                <%= f.text_area :introduction, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-md-4 text-left text-md-center">
                <%= f.label :belong, "属性" %>
              </div>
              <div class="col-md-8">
                <%= f.select :belong, {"大企業勤務": "大企業勤務", "中小企業勤務": "中小企業勤務", "フリーランス": "フリーランス", "学生": "学生", "就職活動中": "就職活動中", "転職を検討中": "転職を検討中"}, { include_blank: "選択してください"}, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-md-4 text-left text-md-center">
                <%= f.label "会員ステータス", class: "col-form-label" %>
              </div>
              <div class="col-sm-7 h-100 d-flex flex-column align-self-center">
                <div class="row">
                  <div class="col-sm-3 h-100 d-flex align-self-center">
                    <%= f.radio_button :is_deleted, :false, class: "mr-2" %>
                    <%= f.label :is_deleted, "有効", value: :false, class: "p-0 m-0" %>
                  </div>
                  <div class="col-sm-3 h-100 d-flex align-self-center">
                  <%= f.radio_button :is_deleted, :true, class: "mr-2" %>
                  <%= f.label :is_deleted, "退会", value: :true, class: "p-0 m-0" %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-md-4 text-left text-md-center">
              </div>
              <div class="col-md-8">
                <%= f.submit "編集内容を保存", class: "btn btn-success col-md-8" %>
              </div>
            </div>
          </div>

        <% end %>

        <div class="form-group">
          <div class="row">
            <div class="col-md-4 text-left text-md-center">
            </div>
            <div class="col-md-8">
              <%= link_to "プロフィールへ戻る", admin_member_path(@member), class: "btn btn-primary col-md-8" %>
            </div>
          </div>
        </div>

      </div>
    </div>

</div>

app/views/admin/members/index.html.erb
<div class = "container p-4">
  <div class = "row justify-content-center pt-3">
    <h3>会員一覧</h3>
  </div>

  <% @members.each do |member| %>
    <div class="row justify-content-center py-3">

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">会員ID</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= member.id %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">氏名</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <%= link_to member.last_name+"　"+member.first_name, admin_member_path(member) %>
        </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">ニックネーム</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= member.nickname %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">メールアドレス</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= member.email %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">ステータス</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= deleted_message(member) %></div>
      </div>

    </div>
  <% end %>

  <div class="row justify-content-center py-4">
    <%= paginate @members, theme: "twitter-bootstrap-4" %>
  </div>

  <div class="row justify-content-center pb-4">
    <%= link_to "TOPへ戻る", admin_path, class: "btn btn-primary col-sm-3" %>
  </div>
</div>

app/views/admin/members/member_jobs.html.erb
<div class = "container p-4">
  <div class = "row justify-content-center pt-3">
    <h3><%= @member.nickname %>さんの職業投稿履歴</h3>
  </div>
    <% @jobs.each do |job| %>
      <div class="row justify-content-center py-3">

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">投稿日</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= job.created_at.strftime("%Y/%m/%d") %></div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">職業ジャンル</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= job.genre.name %></div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">職業名</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <% if job.is_published? %>
              <%= link_to job_path(job) do %>
                <%= job.name %>
              <% end %>
            <% else %>
              <%= job.name %>
            <% end %>
          </div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">管理人との連絡事項</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= contact_message(job) %>
          </div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">公開/非公開</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= published_message(job) %>
          </div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">管理者確認</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= checked_message(job) %>
          </div>
        </div>

      </div>
    <% end %>


  <div class="row justify-content-center">
    <%= paginate @jobs, theme: "twitter-bootstrap-4" %>
  </div>

  <div class="row justify-content-center py-4">
    <%= link_to "プロフィールへ戻る", admin_member_path(@member) , class: "btn btn-primary col-sm-3" %>
  </div>
</div>

app/views/admin/members/member_themes.html.erb
<div class = "container p-4">
  <div class = "row justify-content-center pt-3">
    <h3><%= @member.nickname %>さんのテーマ投稿履歴</h3>
  </div>
  <% @themes.each do |theme| %>
    <div class="row justify-content-center py-3">

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">投稿日</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= theme.created_at.strftime("%Y/%m/%d") %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">職業名</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= theme.jobs.first.name %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">テーマ</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <% if theme.is_published? %>
            <%= link_to job_theme_path(theme.jobs.first,theme) do %>
              <%= theme.name %>
            <% end %>
          <% else %>
            <%= theme.name %>
          <% end %>
        </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">管理人との連絡事項</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <%= contact_message(theme) %>
        </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">公開/非公開</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= published_message(theme) %>
          </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">管理者確認</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= checked_message(theme) %>
          </div>
      </div>

    </div>
    <% end %>

  <div class="row justify-content-center">
    <%= paginate @themes, theme: "twitter-bootstrap-4" %>
  </div>

  <div class="row justify-content-center py-4">
    <%= link_to "プロフィールへ戻る", admin_member_path(@member), class: "btn btn-primary col-sm-3" %>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class = "container p-4">
  <div class = "row justify-content-center pt-3">
    <h3>会員情報詳細</h3>
  </div>

  <div class="row py-4">

    <div class="col-sm-2 p-2">
      <div class="row justify-content-center">
        <div class="d-flex align-items-center">
          <div class="member-icon">
          <%= image_tag @member.get_profile_image(200,200) %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-10 ">
      <div class="row justify-content-center">

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">会員ID</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @member.id %></div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">氏名</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= @member.last_name %><%= "　" %><%=@member.first_name %>
          </div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">ニックネーム</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @member.nickname %></div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">メールアドレス</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @member.email %></div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">自己紹介文</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @member.introduction %></div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">属性</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @member.belong %></div>
        </div>

        <div class="row col-10 justify-content-center">
          <div class="col-md-5 text-center border border-white bg-info text-white">会員ステータス</div>
            <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= deleted_message(@member) %></div>
        </div>

      </div>
    </div>

  </div>

  <div class="row justify-content-center my-3">
    <h5>投稿職業一覧　</h5><h5 class="mx-5"><%= link_to "一覧を見る", member_jobs_admin_member_path(@member), class: "btn btn-primary" %></h5>
    <h5>投稿テーマ一覧</h5><h5 class="mx-5"><%= link_to "一覧を見る", member_themes_admin_member_path(@member), class: "btn btn-primary" %></h5>
  </div>

  <div class="row justify-content-center pt-4">
   <%= link_to "編集する", edit_admin_member_path(@member), class: "btn btn-success col-sm-4" %>
  </div>

  <div class="row justify-content-center py-4">
    <%= link_to "会員一覧へ戻る", admin_members_path, class: "btn btn-info col-sm-4" %>
  </div>
</div>