config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#new_guest"
  end

  root to: "public/homes#top"
  get "about"=> "public/homes#about"
  get "admin"=> "admin/homes#top"
  patch "members/withdraw"=> "public/members#withdraw"
  get "search" => "public/searches#search"

  #【会員側】Deviseを使った新規登録画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "members" => "public/members#dummy"

  #【会員側】テーマ投稿画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "/jobs/:job_id/themes" => "public/themes#dummy"

  #【管理者側】ジャンル名編集画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "/admin/genres/:id" => "admin/genres#dummy"

  namespace :admin do
    resources :members, only: %i(update edit show index) do
      member do
        get :member_jobs
        get :member_themes
      end
    end
    resources :genres, only: %i(index edit create update)
    resources :jobs, only: %i(index show edit update)
    resources :themes, only: %i(index)
    resources :jobs do
      resources :themes, only: %i(edit update) do
        get :theme_in_job, on: :collection
      end
    end
    resources :reports, only: %i(index show edit update)
  end

  #【管理者側】テーマ編集画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "admin/jobs/:job_id/themes/:id" => "admin/themes#dummy"

  scope module: :public do
    resources :members, only: %i(update edit show) do
      get :confirm, on: :collection
      member do
        get :member_jobs
        get :member_themes
        get :member_favorites
        get :member_comment_replies
      end
    end
    resources :jobs, only: %i(new create index show) do
      resources :themes, only: %i(new create show) do
        resources :comments, only: %i(create destroy) do
          resource :favorites, only: %i(create destroy)
          resources :reports, only: %i(new create)
          resources :replies, only: %i(index new create destroy)
        end
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :member
  belongs_to :genre

  has_many :comments
  has_many :theme_in_jobs
  has_many :themes, through: :theme_in_jobs

  validates :name, presence: true

  def self.search_for(method, word)
    case method
    when "perfect_match"
      where("name LIKE ?", "#{word}")
    when "forward_match"
      where("name LIKE ?","#{word}%")
    when "backward_match"
      where("name LIKE ?","%#{word}")
    when "partial_match"
      where("name LIKE ?","%#{word}%")
    else
      all
    end
  end

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::AdminController

  def index
    @jobs = Job.all.order(created_at: :desc).page(params[:page]).per(5)
    @unconfirmed_jobs = Job.where(is_checked: false)
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_update_params)
      redirect_to admin_job_path(@job), notice: "更新が成功しました!"
    else
      flash[:notice] = "更新が正常に行われませんでした。内容をご確認ください。"
      render :edit
    end
  end

  private
    def job_update_params
      params.require(:job).permit(:genre_id, :name, :contact, :is_published, :is_checked)
    end

end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
  include HasIsPublished
  include HasIsChecked
  include HasContact
end

app/views/admin/jobs/edit.html.erb
<div class="container p-4">
  <div class = "row justify-content-center pt-3">
    <h3>職業情報編集</h3>
  </div>
  <div class="row justify-content-center p-4">
    <div class="w-75">
      <%= form_with model: @job, url:admin_job_path(@job), local:true do |f| %>

        <div class="form-group">
          <div class="row">
            <div class="col-md-3 text-left text-md-left">
              <%= f.label :genre_id, "職業ジャンル" %>
            </div>
            <div class="col-md-9">
              <% if @job.genre %>
                <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name, @job.genre.id), include_blank: "ジャンルを選択してください" %>
              <% else %>
                <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), include_blank: "ジャンルを選択してください" %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-3 text-left text-md-left">
              <%= f.label :name, "職業名" %>
            </div>
            <div class="col-md-9">
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-3 text-left text-md-left">
              <%= f.label :contact, "管理人への連絡事項" %>
            </div>
            <div class="col-md-9">
              <%= f.text_area :contact, placeholder: "連絡事項がありましたらご入力下さい", class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-3 h-100">
              <%= f.label "表示ステータス", class: "col-form-label" %>
            </div>
            <div class="col-md-7 h-100 d-flex flex-column align-self-center">
              <div class="row">
                <div class="col-md-3 h-100 d-flex align-self-center">
                  <%= f.radio_button :is_published, :false, class: "mr-2"  %>
                  <%= f.label :is_published, "未公開", value: :false, class: "p-0 m-0" %>
                </div>
                <div class="col-md-3 h-100 d-flex align-self-center">
                  <%= f.radio_button :is_published, :true, class: "mr-2" %>
                  <%= f.label :is_published, "公開", value: :true, class: "p-0 m-0" %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-3 h-100">
              <%= f.label "確認ステータス", class: "col-form-label" %>
            </div>
            <div class="col-md-7 h-100 d-flex flex-column align-self-center">
              <div class="row">
                <div class="col-md-3 h-100 d-flex align-self-center">
                  <%= f.radio_button :is_checked, :false, class: "mr-2" %>
                  <%= f.label :is_checked, "未確認", value: :false, class: "p-0 m-0" %>
                </div>
                <div class="col-md-3 h-100 d-flex align-self-center">
                  <%= f.radio_button :is_checked, :true, class: "mr-2" %>
                  <%= f.label :is_checked, "確認済み", value: :true, class: "p-0 m-0" %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row justify-content-center pt-4">
          <%= f.submit "更新", class: "btn btn-success col-md-5" %>
        </div>
        <div class="row justify-content-center py-4">
          <%= link_to "職業詳細へ戻る", admin_job_path(@job), class: "btn btn-primary col-md-5" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/jobs/index.html.erb
<div class = "container p-4">

  <% if @unconfirmed_jobs.count > 0 %>
    <% @unconfirmed_jobs.each do |unconfirmed_job| %>
    <h4 class="row text-danger">
      ※職業id<div class="font-weight-bold"><%= unconfirmed_job.id %></div>の<div class="font-weight-bold"><%= unconfirmed_job.name %></div>が未確認です。
    </h4>
    <% end %>
  <% end %>

  <div class = "row justify-content-center pt-3">
    <h3>職業一覧</h3>
  </div>

  <% @jobs.each do |job| %>
    <div class="row justify-content-center py-3">

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">職業id</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= job.id %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">ジャンル</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= job.genre.name %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">職業名</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= link_to job.name, admin_job_path(job) %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">投稿者</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= link_to job.member.nickname, admin_member_path(job.member) %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">表示ステータス</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= published_message(job) %>
          </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">確認ステータス</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= checked_message(job) %>
          </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">リンク先</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <% if job.is_published? %>
              <%= link_to "テーマ一覧へ進む", job_path(job) %>
            <% else %>
              <div class="text-danger font-weight-bold">未公開です</div>
            <% end %>
        </div>
      </div>

    </div>
  <% end %>

  <div class="row justify-content-center py-4 ">
    <%= paginate @jobs, theme: "twitter-bootstrap-4" %>
  </div>

  <div class="row justify-content-center pb-4">
    <%= link_to "TOPへ戻る", admin_path, class: "btn btn-primary col-sm-3" %>
  </div>

</div>

app/views/admin/jobs/show.html.erb
 <div class = "container p-4">
  <div class = "row justify-content-center pt-3">
    <h3>職業詳細</h3>
  </div>

  <div class="row justify-content-center py-3">

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">職業id</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @job.id %></div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">ジャンル</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @job.genre.name %></div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">職業名</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @job.name %></div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">管理人への連絡事項</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">
        <%= contact_message(@job) %>
      </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">投稿者</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">
        <%= link_to @job.member.nickname, admin_member_path(@job.member) %>
      </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">表示ステータス</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <%= published_message(@job) %>
        </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">確認ステータス</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <%= checked_message(@job) %>
        </div>
    </div>

  </div>

  <div class="row justify-content-center pt-4">
    <%= link_to "編集する", edit_admin_job_path(@job), class: "btn btn-success col-sm-3" %>
  </div>

  <div class="row justify-content-center py-4">
    <%=link_to "職業一覧へ戻る", admin_jobs_path, class: "btn btn-primary col-sm-3" %>
  </div>
</div>