config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#new_guest"
  end

  root to: "public/homes#top"
  get "about"=> "public/homes#about"
  get "admin"=> "admin/homes#top"
  patch "members/withdraw"=> "public/members#withdraw"
  get "search" => "public/searches#search"

  #【会員側】Deviseを使った新規登録画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "members" => "public/members#dummy"

  #【会員側】テーマ投稿画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "/jobs/:job_id/themes" => "public/themes#dummy"

  #【管理者側】ジャンル名編集画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "/admin/genres/:id" => "admin/genres#dummy"

  namespace :admin do
    resources :members, only: %i(update edit show index) do
      member do
        get :member_jobs
        get :member_themes
      end
    end
    resources :genres, only: %i(index edit create update)
    resources :jobs, only: %i(index show edit update)
    resources :themes, only: %i(index)
    resources :jobs do
      resources :themes, only: %i(edit update) do
        get :theme_in_job, on: :collection
      end
    end
    resources :reports, only: %i(index show edit update)
  end

  #【管理者側】テーマ編集画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "admin/jobs/:job_id/themes/:id" => "admin/themes#dummy"

  scope module: :public do
    resources :members, only: %i(update edit show) do
      get :confirm, on: :collection
      member do
        get :member_jobs
        get :member_themes
        get :member_favorites
        get :member_comment_replies
      end
    end
    resources :jobs, only: %i(new create index show) do
      resources :themes, only: %i(new create show) do
        resources :comments, only: %i(create destroy) do
          resource :favorites, only: %i(create destroy)
          resources :reports, only: %i(new create)
          resources :replies, only: %i(index new create destroy)
        end
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :member
  belongs_to :comment
  belongs_to :reply, optional: true

  validates :reason, presence: true
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController

  def index
    @reports = Report.all.order(created_at: :desc).page(params[:page]).per(5)
    @unconfirmed_reports = Report.where(is_checked: false)
  end

  def show
    @report = Report.find(params[:id])
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params)
      redirect_to admin_report_path(@report), notice: "内容を更新しました。"
    else
      render :edit
    end
  end

  def report_params
    params.require(:report).permit(:is_checked)
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
  include HasIsChecked
end

app/views/admin/reports/edit.html.erb
 <div class = "container p-4">
  <div class = "row justify-content-center pt-3">
    <h3>通報編集</h3>
  </div>

  <%= form_with model: @report, url: admin_report_path(@report,reply_id: params[:reply_id]), local:true do |f| %>

    <div class="row justify-content-center py-3">

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">通報id</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @report.id %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">通報日時</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <%= @report.created_at.strftime("%Y年%m月%d日 %H:%M") %>
        </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">対象コメント</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <% if @report.reply_id? %>
            <%= @report.reply.reply %>
          <% else %>
            <%= @report.comment.comment %>
          <% end %>
        </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">コメント投稿日</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @report.created_at.strftime("%Y年%m月%d日 %H:%M") %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">通報者</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @report.member.nickname %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">通報理由</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @report.reason %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-warning text-dark">確認ステータス</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark ">
            <div class="d-flex flex-column align-self-center">
              <div class="row">
                <div class="col-md-5 h-100 d-flex align-self-center">
                  <%= f.radio_button :is_checked, :false, class: "mr-2"%>
                  <%= f.label :is_checked, "未確認", value: :false, class: "p-0 m-0" %>
                </div>
                <div class="col-md-5 h-100 d-flex align-self-center">
                  <%= f.radio_button :is_checked, :true, class: "mr-2"%>
                  <%= f.label :is_checked, "確認済", value: :true, class: "p-0 m-0" %>
                </div>
              </div>
            </div>
          </div>
      </div>

    </div>

    <div class="row justify-content-center pt-4">
      <%= f.submit "更新する", class: "btn btn-success col-sm-3" %>
    </div>

  <% end %>

  <div class="row justify-content-center py-4">
    <%=link_to "通報一覧へ戻る", admin_reports_path, class: "btn btn-primary col-sm-3" %>
  </div>
</div>

app/views/admin/reports/index.html.erb
<div class = "container p-4">
  <% if @unconfirmed_reports.count > 0 %>
    <% @unconfirmed_reports.each do |unconfirmed_report| %>
    <h4 class="row text-danger">
      ※通報id<div class="font-weight-bold"><%= unconfirmed_report.id %></div>が未確認です。
    </h4>
    <% end %>
  <% end %>
  <div class = "row justify-content-center pt-3">
    <h3>通報一覧</h3>
  </div>

  <% @reports.each do |report| %>
    <div class="row justify-content-center py-3">

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">通報id</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= report.id %></div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">通報日時</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <%= report.created_at.strftime("%Y年%m月%d日 %H:%M") %>
        </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">対象コメント</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <% if report.reply_id? %>
            <%= link_to report.reply.reply, admin_report_path(report) %>
          <% else %>
            <%= link_to report.comment.comment, admin_report_path(report) %>
          <% end %>
        </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">通報者</div>
        <div class="col-md-5 text-center border border-dark bg-white text-dark">
          <%= link_to report.member.nickname , admin_member_path(report.member) %>
        </div>
      </div>

      <div class="row col-10 justify-content-center">
        <div class="col-md-5 text-center border border-white bg-info text-white">確認ステータス</div>
          <div class="col-md-5 text-center border border-dark bg-white text-dark">
            <%= checked_message(report) %>
          </div>
      </div>

    </div>
  <% end %>

  <div class="row justify-content-center py-4">
    <%= paginate @reports, theme: "twitter-bootstrap-4" %>
  </div>

  <div class="row justify-content-center pb-4">
    <%= link_to "TOPへ戻る", admin_path, class: "btn btn-primary col-sm-3" %>
  </div>
</div>

app/views/admin/reports/show.html.erb
 <div class = "container p-4">
  <div class = "row justify-content-center pt-3">
    <h3>通報詳細</h3>
  </div>

  <div class="row justify-content-center py-3">

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">通報id</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark"><%= @report.id %></div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">通報日時</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">
        <%= @report.created_at.strftime("%Y年%m月%d日 %H:%M") %>
      </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">区分</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">
        <% if @report.reply_id? %>
          <div class="text-info font-weight-bold">返信コメント</div>
        <% else %>
          <div class="text-info font-weight-bold">コメント</div>
        <% end %>
      </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">対象コメント</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">

        <!--★通報がコメントに対するものか、返信コメントに対するものかを判別する-->
        <% if @report.reply_id? %>

          <!--△返信コメントの通報の場合に、返信元のコメントが生きているかを判別する-->
          <% if @report.reply.comment.is_published? %>

            <!--◎返信元のコメントが生きている場合、（通報対象である）返信コメントが生きているかを判別する-->
            <% if @report.reply.is_published? %>
              <%= link_to @report.reply.reply, job_theme_comment_replies_path(@report.comment.job, @report.comment.theme, @report.comment) %>
            <% else %>
              <div class="text-danger font-weight-bold">すでに削除済みです</div>
            <% end %>

          <!--△返信コメントに対する通報の場合で、返信元のコメントがすでに（論理）削除されている場合-->
          <% else %>
            <div class="text-danger font-weight-bold">返信元のコメントが削除済みです</div>
          <% end %>

        <!--★コメントに対する通報の場合-->
        <% else %>

          <% if @report.comment.is_published? %>
            <%= link_to @report.comment.comment, job_theme_path(@report.comment.job, @report.comment.theme) %>
          <% else %>
            <div class="text-danger font-weight-bold">すでに削除済みです</div>
          <% end %>

        <% end %>

      </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">コメント投稿日</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">
        <%= @report.comment.created_at.strftime("%Y年%m月%d日 %H:%M") %>
      </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">通報者</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">
        <%= link_to @report.member.nickname, admin_member_path(@report.member) %>
      </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">通報理由</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">
        <%= @report.reason %>
      </div>
    </div>

    <div class="row col-10 justify-content-center">
      <div class="col-md-5 text-center border border-white bg-info text-white">確認ステータス</div>
      <div class="col-md-5 text-center border border-dark bg-white text-dark">
        <%= checked_message(@report) %>
      </div>
    </div>

  </div>

  <div class="row justify-content-center pt-4">
    <%= link_to "編集する", edit_admin_report_path(@report), class: "btn btn-success col-sm-3" %>
  </div>

  <div class="row justify-content-center py-4">
    <%=link_to "通報一覧へ戻る", admin_reports_path, class: "btn btn-primary col-sm-3" %>
  </div>
</div>