config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#new_guest"
  end

  root to: "public/homes#top"
  get "about"=> "public/homes#about"
  get "admin"=> "admin/homes#top"
  patch "members/withdraw"=> "public/members#withdraw"
  get "search" => "public/searches#search"

  #【会員側】Deviseを使った新規登録画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "members" => "public/members#dummy"

  #【会員側】テーマ投稿画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "/jobs/:job_id/themes" => "public/themes#dummy"

  #【管理者側】ジャンル名編集画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "/admin/genres/:id" => "admin/genres#dummy"

  namespace :admin do
    resources :members, only: %i(update edit show index) do
      member do
        get :member_jobs
        get :member_themes
      end
    end
    resources :genres, only: %i(index edit create update)
    resources :jobs, only: %i(index show edit update)
    resources :themes, only: %i(index)
    resources :jobs do
      resources :themes, only: %i(edit update) do
        get :theme_in_job, on: :collection
      end
    end
    resources :reports, only: %i(index show edit update)
  end

  #【管理者側】テーマ編集画面で、エラーメッセージが表示されている時にリロードをするとRouting Errorが出てしまう事への対処
  get "admin/jobs/:job_id/themes/:id" => "admin/themes#dummy"

  scope module: :public do
    resources :members, only: %i(update edit show) do
      get :confirm, on: :collection
      member do
        get :member_jobs
        get :member_themes
        get :member_favorites
        get :member_comment_replies
      end
    end
    resources :jobs, only: %i(new create index show) do
      resources :themes, only: %i(new create show) do
        resources :comments, only: %i(create destroy) do
          resource :favorites, only: %i(create destroy)
          resources :reports, only: %i(new create)
          resources :replies, only: %i(index new create destroy)
        end
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareMyjob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c8df76fea2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="wrapper">
      <header class="fixed-top">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="/">
              <%= image_tag asset_path("logo.jpg"), class: "logo" %>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
              <ul class="navbar-nav me-auto">
                <!--顧客ログイン時-->
                <% if member_signed_in? %>
                  <li class="nav-item  mx-3">
                    <%= link_to about_path, class: "nav-link text-dark" do %>
                      <i class="fa-regular fa-comments">About</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to jobs_path, class: "nav-link text-dark" do %>
                      <i class="fa-solid fa-star">Jobs</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to member_path(current_member), class: "nav-link text-dark" do %>
                      <i class="fa-solid fa-user-gear">Mypage</i>
                    <% end %>
                  </li>
                  <% if !current_member.guest? %>
                    <li class="nav-item mx-3">
                      <%= link_to member_favorites_member_path(current_member), class: "nav-link text-dark" do %>
                        <i class="fa-solid fa-paperclip">Bookmarks</i>
                      <% end %>
                    </li>
                  <% else %>
                    <li class="nav-item _disabled mx-3">
                      <%= link_to "#", class: "nav-link text-dark" do %>
                        <i class="fa-solid fa-paperclip">Bookmarks</i>
                      <% end %>
                    </li>
                  <% end %>
                  <li class="nav-item mx-3">
                    <%= link_to destroy_member_session_path, class: "nav-link text-dark", method: :delete do %>
                    <i class="fa-solid fa-right-from-bracket">Log out</i>
                    <% end %>
                  </li>

                <!--管理者ログイン時-->
                <% elsif admin_signed_in? %>
                  <li class="nav-item mx-3">
                    <%= link_to admin_members_path, class: "nav-link text-dark" do %>
                      <i class="fa-solid fa-star">会員一覧</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to admin_jobs_path, class: "nav-link text-dark" do %>
                      <i class="fa-solid fa-star">職業一覧</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to admin_themes_path, class: "nav-link text-dark" do %>
                      <i class="fa-solid fa-star">テーマ一覧</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to admin_reports_path, class: "nav-link text-dark" do %>
                      <i class="fa-solid fa-star">通報一覧</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to admin_genres_path, class: "nav-link text-dark" do %>
                      <i class="fa-solid fa-star">ジャンル一覧</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to destroy_admin_session_path, class: "nav-link text-dark", method: :delete do %>
                      <i class="fa-solid fa-right-from-bracket">ログアウト</i>
                    <% end %>
                  </li>

                <!--顧客・管理者ログアウト時-->
                <% else %>
                  <li class="nav-item mx-3">
                    <%= link_to about_path, class: "nav-link text-dark" do %>
                      <i class="fa-regular fa-comments">About</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to  new_member_registration_path, class: "nav-link text-dark" do %>
                    <i class="fa-solid fa-user-plus">Sign up</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to  new_member_session_path, class: "nav-link text-dark" do %>
                    <i class="fa-solid fa-right-to-bracket">Log In</i>
                    <% end %>
                  </li>
                  <li class="nav-item mx-3">
                    <%= link_to  members_guest_sign_in_path, method: :post, class: "nav-link text-dark" do %>
                    <i class="fa-solid fa-door-open">Guest Login（閲覧用）</i>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <% if flash[:notice]%>
          <div class="alert alert-warning" role="alert"><%=flash[:notice] %></div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning" role="alert"><%= flash[:alert] %></div>
        <% end %>
        <%= yield %>
      </main>
      <footer class="p-2 fixed-bottom">
        <div class= "footer-container">
          <div class = "row">
            <div class="col-1">
              <!--管理者でも会員でもログインしていない状態のみ、鍵のマークを表示させる-->
              <% unless admin_signed_in? or  member_signed_in? %>
                <%= link_to  new_admin_session_path, class: "nav-link text-dark" do %>
                  <i class="fa-solid fa-key"></i>
                <% end %>
              <% end %>
            </div>
            <% if admin_signed_in? %>
              <div class="text-center col-11">
                <%= link_to admin_path do %>《TOPへ移動する》<% end %>
              </div>
            <% else %>
              <div class="text-center col-11">© 2022 Share MyJob. ALL RIGHTS RESERVED.</div>
            <% end %>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>